"""
Chat routes for the Antigravity Mobile Connect bridge.

Phase 1: Real agent integration with streaming, action dispatch,
change review, and artifact endpoints.
"""

from typing import Any, Dict, List

from fastapi import APIRouter, WebSocket, WebSocketDisconnect

from server.bridge import bridge
from server.ws_hub import ws_manager

router = APIRouter(prefix="/api/chat", tags=["chat"])


@router.post("/send")
async def send_message(payload: Dict[str, Any]) -> Dict[str, Any]:
    """Send a chat message to the agent with simulated streaming.

    The response is generated by the real GeminiAgent, then streamed
    to all WebSocket clients in chunks for a streaming visual effect.

    Args:
        payload: Dict with a "message" key.

    Returns:
        Complete agent response dict.
    """
    message = payload.get("message", "")

    if bridge.is_processing:
        return {
            "role": "assistant",
            "content": "⏳ Agent is already processing a message. Please wait.",
            "status": "busy",
        }

    # Use streaming callback to push chunks via WebSocket
    callback = ws_manager.make_stream_callback()
    response = await bridge.send_message_streaming(message, callback)

    return response


@router.get("/history")
async def get_chat_history():
    """Return the current session chat history.

    Returns:
        List of message dicts.
    """
    return bridge.get_chat_history()


@router.post("/action")
async def chat_action(payload: Dict[str, Any]) -> Dict[str, Any]:
    """Execute a chat action (Run, Reject, Expand, etc.).

    Args:
        payload: Dict with "action" and optional "params" keys.

    Returns:
        Action result dict.
    """
    action = payload.get("action", "")
    params = payload.get("params", {})

    result = bridge.execute_action(action, params)

    # Broadcast the action result to all WebSocket clients
    await ws_manager.broadcast_action_result(action, result)

    return result


@router.get("/changes")
async def get_changes() -> Dict[str, Any]:
    """Get pending file changes in the current workspace.

    Returns:
        Dict with changed files and their status.
    """
    return bridge.get_pending_changes()


@router.get("/changes/{file_path:path}")
async def get_file_diff(file_path: str) -> Dict[str, Any]:
    """Get the unified diff for a specific file.

    Args:
        file_path: Relative path to the file in the workspace.

    Returns:
        Dict with the diff content.
    """
    return bridge.get_file_diff(file_path)


@router.post("/changes/review")
async def review_change(payload: Dict[str, Any]) -> Dict[str, Any]:
    """Approve or reject changes for a specific file.

    Args:
        payload: Dict with "file" and "action" (approve/reject) keys.

    Returns:
        Review result dict.
    """
    file_path = payload.get("file", "")
    action = payload.get("action", "")

    if not file_path or action not in ("approve", "reject"):
        return {"status": "error", "message": "Invalid file or action."}

    result = bridge.review_change(file_path, action)

    # Broadcast updated changes
    await ws_manager.broadcast({
        "type": "changes_update",
        "data": bridge.get_pending_changes(),
    })

    return result


@router.post("/changes/review-all")
async def review_all_changes(payload: Dict[str, Any]) -> Dict[str, Any]:
    """Approve or reject all pending changes.

    Args:
        payload: Dict with "action" (approve/reject) key.

    Returns:
        Batch review result dict.
    """
    action = payload.get("action", "")
    if action not in ("approve", "reject"):
        return {"status": "error", "message": "Invalid action."}

    changes = bridge.get_pending_changes()
    results = []
    for file_info in changes.get("files", []):
        result = bridge.review_change(file_info["path"], action)
        results.append(result)

    # Broadcast updated changes
    await ws_manager.broadcast({
        "type": "changes_update",
        "data": bridge.get_pending_changes(),
    })

    return {
        "action": action,
        "status": "completed",
        "count": len(results),
        "results": results,
    }


@router.get("/artifacts")
async def list_artifacts() -> List[Dict[str, Any]]:
    """List all artifacts in the artifacts/ directory.

    Returns:
        List of artifact file dicts.
    """
    return bridge.list_artifacts()


@router.get("/artifacts/{artifact_path:path}")
async def get_artifact(artifact_path: str) -> Dict[str, Any]:
    """Get the content of a specific artifact.

    Args:
        artifact_path: Relative path within the artifacts directory.

    Returns:
        Dict with artifact content and metadata.
    """
    return bridge.get_artifact_content(artifact_path)
